#!/bin/bash

rm -rf dist && \
lerna exec --parallel -- babel . -d dist --ignore node_modules,dist --config-file=../../.babelrc.js && \
mkdir -p ./.docz/public && \
cp ./packages/core/reset.css ./.docz/public/reset.css
cp ./packages/core/reset.css ./packages/core/dist/reset.css
