#!/bin/bash

git checkout origin master && \
git pull --rebase origin master && \
./scripts/clean && \
npm ci && \
./scripts/build && \
lerna version --force-publish && \
lerna publish from-package && \
git checkout origin develop && \
git merge master && \
git push origin develop
